# yaml-language server: $schema=https://json.schemastore.org/github-action.json

name: Infra Code Linting & Testing
on:
  push:
    paths:
      - "ops/**"
      - ".github/workflows/**"

env:
  # renovate: datasource=github-releases depName=pnpm/pnpm versioning=semver
  PNPM_VERSION: v8.7.0

jobs:
  cdk-test:
    strategy:
      fail-fast: false
      matrix:
        task: [prettier, eslint, tsc, test]
    defaults:
      run:
        working-directory: ./ops/
    name: ralphbot-cdk-stack-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: pnpm
          cache-dependency-path: ./ops/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - run: |
          pnpm ${{ matrix.task }}
