name: Ralphbot Infra Stack Test
on:
  push:
    paths:
      - "ops/**"
      - ".github/workflows/ralphbot-infra-lint.yaml"
      - "src/**" #Temporary hack, until golang source code linting has been added.

env:
  COMMIT: ${GITHUB_SHA}
  CDK_IMAGE_NAMETAG: cdk-ralphbot

jobs:
  cdk-test:
    strategy:
      fail-fast: true
      matrix:
        task: [prettier, eslint, tsc, test]
    defaults:
      run:
        working-directory: ./ops/
    name: ralphbot-cdk-stack-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set IMAGE_TAG env
        run: |
          echo "IMAGE_TAG="$(date '+%Y.%m.%d'.${GITHUB_SHA::6})"" >> $GITHUB_ENV

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Login to Amazon Public ECR"
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: "Build CDK App"
        run: |
          docker build --tag ${{ env.CDK_IMAGE_NAMETAG }}:$IMAGE_TAG .

      - run: |
          docker run -i ${{ env.CDK_IMAGE_NAMETAG }}:$IMAGE_TAG ${{ matrix.task }}
