# yaml-language server: $schema=https://json.schemastore.org/github-action.json

name: Bot Code Linting & Testing
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"

env:
  WORK_DIR: ./src

jobs:
  check-tidy:
    runs-on: ubuntu-latest
    name: ralphbot-source-check-deps
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{env.WORK_DIR}}/go.mod
          cache: true
          cache-dependency-path: ${{env.WORK_DIR}}/go.sum

      - name: Check 'go mod tidy' was run
        working-directory: ${{env.WORK_DIR}}
        run: make deps

  go-lint:
    runs-on: ubuntu-latest
    name: ralphbot-source-lint
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{env.WORK_DIR}}/go.mod
          cache: true
          cache-dependency-path: ${{env.WORK_DIR}}/go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{env.WORK_DIR}}
          args: "--timeout=5m"

  go-test:
    runs-on: ubuntu-latest
    name: ralphbot-source-go-test
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{env.WORK_DIR}}/go.mod
          cache: true
          cache-dependency-path: ${{env.WORK_DIR}}/go.sum

      - name: Test
        working-directory: ${{env.WORK_DIR}}
        run: |
          go test ./...
