name: Ralphbot PR Actions
on: 
  push:
    branches:
      - ci-cd

env:
  COMMIT: ${GITHUB_SHA}

jobs:
  cdk:
    name: ralphbot-ops-stack
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ops/
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set VERSION env #Use a bash expression to define a variable for job
        run: echo "VERSION=$(date '+%Y.%m.%d'.${GITHUB_SHA::6})" >> $GITHUB_ENV
      - 
        name: "Build CDK App"
        run: |
          docker build --tag cdk-ralphbot:$VERSION .
      -
        name: "Run Prettier"
        run: |
          docker run -i cdk-ralphbot:$VERSION prettier
  #app: