name: Ralphbot Test Actions
on:
  pull_request:
  push:
    branches: 
      - master

env:
  COMMIT: ${GITHUB_SHA}
  APP_IMAGE_NAMETAG: ralphbot
  CDK_IMAGE_NAMETAG: cdk-ralphbot

jobs:
  cdk-test:
    defaults:
      run:
        working-directory: ./ops/
    name: ralphbot-cdk-stack-test
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set VERSION env #Use a bash expression to define a variable for job
        run: echo "VERSION=$(date '+%Y.%m.%d'.${GITHUB_SHA::6})" >> $GITHUB_ENV
      - 
        name: "Build CDK App"
        run: |
          docker build --tag ${{ env.CDK_IMAGE_NAMETAG }}:$VERSION .
      -
        name: "Run prettier"
        run: |
          docker run -i ${{ env.CDK_IMAGE_NAMETAG }}:$VERSION prettier
      -
        name: "Run eslint"
        run: |
          docker run -i ${{ env.CDK_IMAGE_NAMETAG }}:$VERSION eslint
      -
        name: "Run tsc"
        run: |
          docker run -i ${{ env.CDK_IMAGE_NAMETAG }}:$VERSION tsc
  ralphbot-build:
    defaults:
      run:
        working-directory: ./src/
    name: ralphbot-container-build
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set VERSION env #Use a bash expression to define a variable for job
        run: echo "VERSION=$(date '+%Y.%m.%d'.${GITHUB_SHA::6})" >> $GITHUB_ENV
      - 
        name: "Build Ralphbot Container Image"
        run: |
          docker build --tag ${{ env.APP_IMAGE_NAMETAG }}:$VERSION .