name: Ralphbot Test Actions
on:
  pull_request:
    branches: 
      - "*"
    paths:
      - ./src/
  push:
    branches: [master]  

env:
  COMMIT: ${GITHUB_SHA}
  APP_IMAGE_NAMETAG: ralphbot

jobs:
  ralphbot-build:
    defaults:
      run:
        working-directory: ./src/
    name: ralphbot-container-build
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set VERSION env #Use a bash expression to define a variable for job
        run: echo "VERSION=$(date '+%Y.%m.%d'.${GITHUB_SHA::6})" >> $GITHUB_ENV
      - 
        name: "Build Ralphbot Container Image"
        run: |
          docker build --tag ${{ env.APP_IMAGE_NAMETAG }}:$VERSION .