# yaml-language server: $schema=https://json.schemastore.org/github-action.json

name: Infra Code Linting & Testing
on:
  push:
    paths:
      - "ops/**"
      - ".github/workflows/ralphbot-ops-lint.yaml"

env:
  ESLINT_USE_FLAT_CONFIG: "false"

jobs:
  cdk-test:
    strategy:
      fail-fast: false
      matrix:
        task: [prettier, eslint, tsc, test]
    defaults:
      run:
        working-directory: ./ops/
    name: ralphbot-cdk-stack-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          package_json_file: ./ops/package.json

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
          cache-dependency-path: ./ops/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - run: |
          pnpm ${{ matrix.task }}
