name: renovate-config-validator

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
